# Generated by Django 5.2.17 on 2026-09-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0005_agent_rights_cleanup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='right',
            name='object_type',
            field=models.CharField(choices=[('project', 'Project'), ('channel', 'Channel'), ('topic', 'Chat Topic'), ('session', 'Chat Session'), ('persona', 'Persona'), ('mcp_server', 'MCP Server'), ('model_config', 'Model Config'), ('company', 'Company'), ('schedule', 'Persona Schedule'), ('routine', 'Routine'), ('runbook', 'Runbook'), ('hook', 'Inbound Hook'), ('recall', 'Recall Entry'), ('deliverable', 'Deliverable')], max_length=20),
        ),
    ]
