# Generated by Django 5.2.14 on 2026-05-10 16:24

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'workspace_channel',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('is_personal', models.BooleanField(default=False, help_text='Whether this is a personal/private workspace.')),
            ],
            options={
                'db_table': 'governance_company',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_type', models.CharField(choices=[('human', 'Human'), ('persona', 'Persona')], db_index=True, default='human', max_length=20)),
                ('google_sso_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('current_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_active_users', to='nucleus.company')),
            ],
            options={
                'db_table': 'accounts_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Human-readable model name.', max_length=255)),
                ('provider', models.CharField(choices=[('litellm', 'LiteLLM'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('ollama', 'Ollama'), ('azure', 'Azure OpenAI'), ('local', 'Local')], db_index=True, default='litellm', max_length=50)),
                ('model_id', models.CharField(help_text='Provider model identifier.', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('api_base', models.URLField(blank=True, help_text='Optional custom API base URL.', null=True)),
                ('secret_ref', models.CharField(blank=True, help_text='Reference to secret manager entry.', max_length=255, null=True)),
                ('temperature', models.FloatField(default=0.7)),
                ('max_tokens', models.PositiveIntegerField(default=4096)),
                ('context_window', models.PositiveIntegerField(default=8192)),
                ('supports_tools', models.BooleanField(default=False)),
                ('supports_streaming', models.BooleanField(default=True)),
                ('supports_vision', models.BooleanField(default=False)),
                ('supports_audio', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Additional provider-specific runtime configuration.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ai_models', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='nucleus.company')),
            ],
            options={
                'db_table': 'intelligence_ai_model',
            },
        ),
        migrations.CreateModel(
            name='ChatTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=120)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='nucleus.channel')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='nucleus.company')),
            ],
            options={
                'db_table': 'workspace_chat_topic',
            },
        ),
        migrations.AddField(
            model_name='channel',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='nucleus.company'),
        ),
        migrations.CreateModel(
            name='CompanyAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], db_index=True, default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_list', to='nucleus.company')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_invites_sent', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'governance_company_access',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='members',
            field=models.ManyToManyField(related_name='companies', through='nucleus.CompanyAccess', through_fields=('company', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/')),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('locale', models.CharField(default='en', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='human_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_human',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('channels', models.ManyToManyField(blank=True, related_name='knowledge_bases', to='nucleus.channel')),
                ('chat_topics', models.ManyToManyField(blank=True, related_name='knowledge_bases', to='nucleus.chattopic')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='nucleus.company')),
            ],
            options={
                'db_table': 'intelligence_knowledge_base',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(upload_to='knowledge_files/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.BigIntegerField(default=0)),
                ('chroma_collection', models.CharField(blank=True, max_length=255, null=True)),
                ('embedding_status', models.CharField(default='pending', max_length=30)),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='nucleus.knowledgebase')),
            ],
            options={
                'db_table': 'intelligence_knowledge_file',
            },
        ),
        migrations.CreateModel(
            name='MCPServer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('server_type', models.CharField(choices=[('local', 'Local'), ('docker', 'Docker'), ('kubernetes', 'Kubernetes'), ('remote', 'Remote'), ('hosted', 'Hosted / Online')], db_index=True, default='remote', max_length=30)),
                ('transport', models.CharField(choices=[('stdio', 'STDIO'), ('http', 'HTTP'), ('sse', 'SSE'), ('websocket', 'WebSocket')], db_index=True, default='http', max_length=30)),
                ('command', models.TextField(blank=True, help_text='Command for local/stdio MCP server.', null=True)),
                ('url', models.URLField(blank=True, help_text='URL for HTTP/SSE/WebSocket MCP server.', null=True)),
                ('docker_image', models.CharField(blank=True, help_text='Docker image for Docker-based MCP server.', max_length=255, null=True)),
                ('docker_command', models.TextField(blank=True, help_text='Optional Docker run command or entrypoint override.', null=True)),
                ('kubernetes_service', models.CharField(blank=True, help_text='Kubernetes service name or internal DNS.', max_length=255, null=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Non-secret MCP configuration.')),
                ('secret_ref', models.CharField(blank=True, help_text='Secret manager reference. Do not store raw credentials.', max_length=255, null=True)),
                ('timeout_seconds', models.PositiveIntegerField(default=60)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='nucleus.company')),
            ],
            options={
                'db_table': 'intelligence_mcp_server',
            },
        ),
        migrations.CreateModel(
            name='AIAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('agent_type', models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], db_index=True, default='internal', max_length=20)),
                ('external_url', models.URLField(blank=True, help_text='Remote/online agent endpoint.', null=True)),
                ('secret_ref', models.CharField(blank=True, help_text='Secret manager reference for external agent credentials.', max_length=255, null=True)),
                ('system_prompt', models.TextField(blank=True, help_text='Internal agent execution rules. External agents may ignore this.', null=True)),
                ('safety_mode', models.BooleanField(default=True)),
                ('max_steps', models.PositiveIntegerField(default=5)),
                ('allow_parallel_tools', models.BooleanField(default=False)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agents', to='nucleus.aimodel')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='nucleus.company')),
                ('mcp_server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agents', to='nucleus.mcpserver')),
            ],
            options={
                'db_table': 'intelligence_ai_agent',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('source_type', models.CharField(choices=[('model', 'Model'), ('agent', 'Agent')], db_index=True, max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='personas/%Y/%m/')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personas', to='nucleus.aiagent')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='nucleus.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_personas', to=settings.AUTH_USER_MODEL)),
                ('identity_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='persona_profile', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personas', to='nucleus.aimodel')),
            ],
            options={
                'db_table': 'intelligence_persona',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='nucleus.company')),
            ],
            options={
                'db_table': 'workspace_project',
            },
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='knowledge_bases', to='nucleus.project'),
        ),
        migrations.AddField(
            model_name='chattopic',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='nucleus.project'),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('markdown', 'Markdown'), ('code', 'Code'), ('graph', 'Graph'), ('form', 'Form'), ('image', 'Image'), ('file', 'File'), ('audio', 'Audio'), ('video', 'Video'), ('system', 'System'), ('mixed', 'Mixed')], db_index=True, default='text', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('content_json', models.JSONField(blank=True, default=dict, help_text='Forms, graphs, tool outputs, structured AI response, etc.')),
                ('language', models.CharField(blank=True, help_text='Example: en, ur, ar, fr, python, javascript', max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('streaming', 'Streaming'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='completed', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='nucleus.chatmessage')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='nucleus.chattopic')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='nucleus.company')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='nucleus.project')),
            ],
            options={
                'db_table': 'workspace_chat_message',
            },
        ),
        migrations.AddField(
            model_name='channel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='nucleus.project'),
        ),
        migrations.CreateModel(
            name='ChatAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('attachment_type', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF'), ('document', 'Document'), ('audio', 'Audio'), ('video', 'Video'), ('csv', 'CSV'), ('json', 'JSON'), ('other', 'Other')], default='other', max_length=20)),
                ('file', models.FileField(upload_to='chat_attachments/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.BigIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='nucleus.chatmessage')),
            ],
            options={
                'db_table': 'workspace_chat_attachment',
                'indexes': [models.Index(fields=['message'], name='workspace_c_message_5fb686_idx'), models.Index(fields=['attachment_type'], name='workspace_c_attachm_bf0922_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('emoji', models.CharField(max_length=20)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='nucleus.chatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workspace_chat_reaction',
                'indexes': [models.Index(fields=['message', 'emoji'], name='workspace_c_message_af2b7d_idx'), models.Index(fields=['user'], name='workspace_c_user_id_0d3631_idx')],
                'constraints': [models.UniqueConstraint(fields=('message', 'user', 'emoji'), name='uniq_message_user_emoji_reaction')],
            },
        ),
        migrations.CreateModel(
            name='ChatReadMarker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('last_read_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='nucleus.chatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_read_markers', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_markers', to='nucleus.chattopic')),
            ],
            options={
                'db_table': 'workspace_chat_read_marker',
                'indexes': [models.Index(fields=['user', 'topic'], name='workspace_c_user_id_d1c2ad_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'topic'), name='uniq_user_topic_read_marker')],
            },
        ),
        migrations.AddIndex(
            model_name='aimodel',
            index=models.Index(fields=['company', 'provider'], name='intelligenc_company_671d7a_idx'),
        ),
        migrations.AddIndex(
            model_name='aimodel',
            index=models.Index(fields=['company', 'is_active'], name='intelligenc_company_21473e_idx'),
        ),
        migrations.AddConstraint(
            model_name='aimodel',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_ai_model_name_per_company'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_type'], name='accounts_us_user_ty_b6cfc8_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['google_sso_id'], name='accounts_us_google__aa6205_idx'),
        ),
        migrations.AddIndex(
            model_name='companyaccess',
            index=models.Index(fields=['company', 'role'], name='governance__company_008fd0_idx'),
        ),
        migrations.AddIndex(
            model_name='companyaccess',
            index=models.Index(fields=['user', 'is_active'], name='governance__user_id_cefb1f_idx'),
        ),
        migrations.AddConstraint(
            model_name='companyaccess',
            constraint=models.UniqueConstraint(fields=('company', 'user'), name='uniq_company_user_access'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['slug'], name='governance__slug_a93e42_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['is_active'], name='governance__is_acti_9b1455_idx'),
        ),
        migrations.AddIndex(
            model_name='mcpserver',
            index=models.Index(fields=['company', 'server_type'], name='intelligenc_company_e5c5f9_idx'),
        ),
        migrations.AddIndex(
            model_name='mcpserver',
            index=models.Index(fields=['company', 'transport'], name='intelligenc_company_ab5a4e_idx'),
        ),
        migrations.AddIndex(
            model_name='mcpserver',
            index=models.Index(fields=['company', 'is_active'], name='intelligenc_company_3a7ad2_idx'),
        ),
        migrations.AddConstraint(
            model_name='mcpserver',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_mcp_server_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='mcpserver',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('transport', 'stdio'), _negated=True), ('command__isnull', False), _connector='OR'), name='mcp_stdio_requires_command'),
        ),
        migrations.AddConstraint(
            model_name='mcpserver',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('transport__in', ['http', 'sse', 'websocket']), _negated=True), ('url__isnull', False), _connector='OR'), name='mcp_http_sse_ws_requires_url'),
        ),
        migrations.AddIndex(
            model_name='aiagent',
            index=models.Index(fields=['company', 'agent_type'], name='intelligenc_company_9a8833_idx'),
        ),
        migrations.AddIndex(
            model_name='aiagent',
            index=models.Index(fields=['company', 'model'], name='intelligenc_company_4249ff_idx'),
        ),
        migrations.AddIndex(
            model_name='aiagent',
            index=models.Index(fields=['company', 'mcp_server'], name='intelligenc_company_6cdf88_idx'),
        ),
        migrations.AddIndex(
            model_name='aiagent',
            index=models.Index(fields=['company', 'is_active'], name='intelligenc_company_9137b2_idx'),
        ),
        migrations.AddConstraint(
            model_name='aiagent',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_ai_agent_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='aiagent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('agent_type', 'internal'), _negated=True), ('model__isnull', False), _connector='OR'), name='internal_agent_requires_model'),
        ),
        migrations.AddConstraint(
            model_name='aiagent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('agent_type', 'external'), _negated=True), ('external_url__isnull', False), _connector='OR'), name='external_agent_requires_url'),
        ),
        migrations.AddIndex(
            model_name='persona',
            index=models.Index(fields=['company', 'source_type'], name='intelligenc_company_2088d0_idx'),
        ),
        migrations.AddIndex(
            model_name='persona',
            index=models.Index(fields=['company', 'is_active'], name='intelligenc_company_585efe_idx'),
        ),
        migrations.AddConstraint(
            model_name='persona',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_persona_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='persona',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('agent__isnull', True), ('model__isnull', False), ('source_type', 'model')), models.Q(('agent__isnull', False), ('model__isnull', True), ('source_type', 'agent')), _connector='OR'), name='persona_model_or_agent_required'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('company', 'slug'), name='uniq_project_slug_per_company'),
        ),
        migrations.AddIndex(
            model_name='knowledgebase',
            index=models.Index(fields=['company', 'is_active'], name='intelligenc_company_77e0ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgebase',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_knowledge_base_name_per_company'),
        ),
        migrations.AddIndex(
            model_name='chattopic',
            index=models.Index(fields=['company', 'project', 'channel'], name='workspace_c_company_414e76_idx'),
        ),
        migrations.AddConstraint(
            model_name='chattopic',
            constraint=models.UniqueConstraint(fields=('channel', 'slug'), name='uniq_topic_slug_per_channel'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['company', 'project', 'topic'], name='workspace_c_company_413db7_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['topic', 'created_at'], name='workspace_c_topic_i_d74657_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', 'created_at'], name='workspace_c_sender__d7b099_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['message_type'], name='workspace_c_message_30a062_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['status'], name='workspace_c_status_d7e912_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['company', 'project'], name='workspace_c_company_b829f4_idx'),
        ),
        migrations.AddConstraint(
            model_name='channel',
            constraint=models.UniqueConstraint(fields=('project', 'slug'), name='uniq_channel_slug_per_project'),
        ),
    ]
