# Generated by Django 5.2.15 on 2026-06-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleus', '0003_owner_fk_on_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitation',
            options={'default_permissions': ('add', 'view', 'change', 'delete', 'invite', 'remove', 'archive', 'join')},
        ),
        migrations.AddField(
            model_name='invitation',
            name='role',
            field=models.CharField(db_index=True, default='member', help_text='CompanyAccess role to assign when invitation is accepted.', max_length=20),
        ),
    ]
