# Generated by Django 5.2.15 on 2026-07-19 05:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleus', '0005_workspace_operation_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAIConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('embedding_provider', models.CharField(choices=[('fastembed', 'FastEmbed (local ONNX)'), ('litellm', 'LiteLLM (Ollama / OpenAI / Infinity)')], default='fastembed', max_length=50)),
                ('embedding_model', models.CharField(default='nomic-ai/nomic-embed-text-v1.5', help_text='Model name passed to the embedding provider.', max_length=255)),
                ('embedding_base_url', models.URLField(blank=True, default='', help_text='Required when provider=litellm and model runs on Ollama or Infinity.')),
                ('default_llm_model', models.CharField(default='anthropic/claude-haiku-4-5-20251001', help_text='Fallback LLM model when a persona has no model assigned.', max_length=255)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_config', to='nucleus.company')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_config_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company AI Config',
                'db_table': 'intelligence_company_ai_config',
            },
        ),
    ]
