# Generated by Django 5.2.15 on 2026-07-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleus', '0006_companyaiconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='api_key_encrypted',
            field=models.TextField(blank=True, help_text='Fernet-encrypted API key. Do not set directly — use set_api_key().', null=True),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='licence_accepted',
            field=models.BooleanField(default=False, help_text="User must accept the provider's terms of service before this model is active."),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='secret_ref',
            field=models.CharField(blank=True, help_text='Reference to secret manager entry (production: Vault / AWS Secrets Manager).', max_length=255, null=True),
        ),
    ]
