# Generated by Django 5.2.15 on 2026-07-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleus', '0007_aimodel_api_key_licence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='api_key_encrypted',
            field=models.TextField(blank=True, help_text='Fernet-encrypted API key. Do not set directly - use set_api_key().', null=True),
        ),
    ]
