# Generated by Django 5.2.15 on 2026-07-19 07:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleus', '0008_aimodel_api_key_licence'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Short description shown in the template picker.')),
                ('system_prompt', models.TextField(help_text='The actual system prompt content.')),
                ('output_type', models.CharField(choices=[('text', 'Text (Markdown)'), ('code', 'Code'), ('chart', 'Chart (Chart.js)'), ('html', 'HTML'), ('form', 'Form')], db_index=True, default='text', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list, help_text="List of tag strings for filtering (e.g. ['coding', 'python']).")),
                ('is_featured', models.BooleanField(default=False, help_text='Show this template prominently in the picker.')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='nucleus.company')),
            ],
            options={
                'db_table': 'intelligence_prompt_template',
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('system_prompt', models.TextField(help_text='System prompt sent to the model on every AI trigger.')),
                ('output_type', models.CharField(choices=[('text', 'Text (Markdown)'), ('code', 'Code'), ('chart', 'Chart (Chart.js)'), ('html', 'HTML'), ('form', 'Form')], db_index=True, default='text', help_text='Controls model output format and frontend rendering.', max_length=20)),
                ('context_scope', models.JSONField(blank=True, help_text="Optional list of context types to include, e.g. ['chat', 'doc']. Null means all attached context sources are searched.", null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='nucleus.company')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prompt', to='nucleus.persona')),
                ('template', models.ForeignKey(blank=True, help_text='The template this prompt was created from, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_prompts', to='nucleus.prompttemplate')),
            ],
            options={
                'db_table': 'intelligence_prompt',
            },
        ),
        migrations.AddIndex(
            model_name='prompttemplate',
            index=models.Index(fields=['company', 'output_type'], name='intelligenc_company_2a990f_idx'),
        ),
        migrations.AddIndex(
            model_name='prompttemplate',
            index=models.Index(fields=['company', 'is_featured'], name='intelligenc_company_56fa11_idx'),
        ),
        migrations.AddIndex(
            model_name='prompttemplate',
            index=models.Index(fields=['company', 'is_active'], name='intelligenc_company_c66d8d_idx'),
        ),
        migrations.AddConstraint(
            model_name='prompttemplate',
            constraint=models.UniqueConstraint(fields=('company', 'title'), name='uniq_prompt_template_title_per_company'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['company', 'output_type'], name='intelligenc_company_20c290_idx'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['company', 'is_active'], name='intelligenc_company_731360_idx'),
        ),
    ]
