# Generated by Django 5.2.15 on 2026-07-20 07:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleus', '0011_prompt_output_type_simplify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='api_base',
            field=models.URLField(blank=True, help_text='Optional custom API base URL (e.g. Ollama or self-hosted endpoint).', null=True),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='api_key_encrypted',
            field=models.TextField(blank=True, help_text='Fernet-encrypted API key. Do not set directly — use set_api_key().', null=True),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='model_id',
            field=models.CharField(help_text="LiteLLM model string, e.g. 'anthropic/claude-haiku-4-5-20251001'.", max_length=255),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='output_type',
            field=models.CharField(choices=[('text', 'Text (Markdown)'), ('code', 'Code'), ('html', 'HTML')], db_index=True, default='text', help_text='Controls model output format and frontend rendering.', max_length=20),
        ),
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('job_id', models.CharField(db_index=True, max_length=64)),
                ('msg_id', models.CharField(db_index=True, max_length=64)),
                ('model_id', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=50)),
                ('prompt', models.JSONField()),
                ('response', models.TextField(blank=True)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], db_index=True, default='success', max_length=10)),
                ('error', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='nucleus.company')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to='nucleus.persona')),
            ],
            options={
                'db_table': 'intelligence_ai_request_log',
                'indexes': [models.Index(fields=['company', 'persona'], name='intelligenc_company_ab994b_idx'), models.Index(fields=['company', 'created_at'], name='intelligenc_company_2c8171_idx'), models.Index(fields=['job_id'], name='intelligenc_job_id_ca3deb_idx'), models.Index(fields=['msg_id'], name='intelligenc_msg_id_eb75d3_idx')],
            },
        ),
    ]
