# Generated by Django 5.2.15 on 2026-07-21 05:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleus', '0012_alter_aimodel_api_base_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('file', 'File'), ('web', 'Web URL')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='context_sources/%Y/%m/%d/')),
                ('file_size', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField(blank=True, null=True)),
                ('collection_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('error', 'Error')], db_index=True, default='pending', max_length=10)),
                ('error', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='nucleus.company')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_sources', to='nucleus.chattopic')),
            ],
            options={
                'db_table': 'context_source',
                'indexes': [models.Index(fields=['topic', 'type'], name='context_sou_topic_i_bbda9c_idx'), models.Index(fields=['company', 'topic'], name='context_sou_company_93b807_idx'), models.Index(fields=['status'], name='context_sou_status_8d8463_idx')],
            },
        ),
    ]
