# Generated by Django 5.2.15 on 2026-07-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleus', '0013_contextsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextsource',
            name='checksum',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddIndex(
            model_name='contextsource',
            index=models.Index(fields=['topic', 'checksum'], name='context_sou_topic_i_16dda7_idx'),
        ),
    ]
