# Generated by Django 5.2.15 on 2026-07-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleus', '0014_add_checksum_to_context_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, db_index=True, help_text='Per-server display name. Auto-assigned from email on join; editable later.', max_length=50),
        ),
    ]
