# Generated by Django 5.2.17 on 2026-09-07 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleus', '0016_persona_backfill_delete_aiagent'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mcpserver',
            name='mcp_stdio_requires_command',
        ),
        migrations.RemoveConstraint(
            model_name='mcpserver',
            name='mcp_http_sse_ws_requires_url',
        ),
        migrations.AddField(
            model_name='mcpserver',
            name='capability_config',
            field=models.JSONField(blank=True, default=dict, help_text='Internal rows only: the pydantic-ai capability configuration, read and interpreted by nexus-ai. Deliberately opaque here -- nucleus stores and forwards it without validating the shape, which is owned by apps/schemas/trigger.py on the nexus-ai side. Kept separate from `config` below, which belongs to external servers and is already in use (the auto-provisioned filesystem MCP writes root_path into it).'),
        ),
        migrations.AddField(
            model_name='mcpserver',
            name='is_internal',
            field=models.BooleanField(db_index=True, default=False, help_text='True = a pydantic-ai capability configured purely through capability_config. False = a real MCP server reached over a transport.'),
        ),
        migrations.AddConstraint(
            model_name='mcpserver',
            constraint=models.CheckConstraint(condition=models.Q(('is_internal', True), models.Q(('transport', 'stdio'), _negated=True), ('command__isnull', False), _connector='OR'), name='mcp_stdio_requires_command'),
        ),
        migrations.AddConstraint(
            model_name='mcpserver',
            constraint=models.CheckConstraint(condition=models.Q(('is_internal', True), models.Q(('transport__in', ['http', 'sse', 'websocket']), _negated=True), ('url__isnull', False), _connector='OR'), name='mcp_http_sse_ws_requires_url'),
        ),
        migrations.AddConstraint(
            model_name='mcpserver',
            constraint=models.CheckConstraint(condition=models.Q(('is_internal', False), models.Q(('url__isnull', True), ('command__isnull', True), ('docker_image__isnull', True), ('kubernetes_service__isnull', True), ('auth_type', 'none')), _connector='OR'), name='mcp_internal_has_no_endpoint'),
        ),
    ]
