# Generated by Django 6.0.8 on 2026-09-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleus', '0017_mcp_internal_capability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelconfig',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google (Gemini)'), ('deepseek', 'DeepSeek'), ('ollama', 'Ollama (local)'), ('openai_compatible', 'OpenAI-compatible endpoint')], db_index=True, default='openai', max_length=50),
        ),
    ]
