# Generated by Django 5.2.17 on 2026-09-13 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleus', '0018_alter_modelconfig_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='airequestlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='cache_read_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='cache_write_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='cost_usd',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='hop',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='model_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to='nucleus.modelconfig'),
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='requests',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='tool_calls',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_requests', to='nucleus.chattopic'),
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='budget_stopped_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='budget_warned_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='monthly_cost_budget_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='monthly_token_budget',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='prompt',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='airequestlog',
            index=models.Index(fields=['model_config', 'created_at'], name='intelligenc_model_c_c53437_idx'),
        ),
        migrations.AddIndex(
            model_name='airequestlog',
            index=models.Index(fields=['actor', 'created_at'], name='intelligenc_actor_i_6fd199_idx'),
        ),
        migrations.AddIndex(
            model_name='airequestlog',
            index=models.Index(fields=['persona', 'actor', 'created_at'], name='intelligenc_persona_02fa50_idx'),
        ),
    ]
