# Generated by Django 5.2.17 on 2026-09-21 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleus', '0019_project_brief'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyaiconfig',
            name='utility_model',
            field=models.ForeignKey(blank=True, help_text="Model config used for the server's utility passes; falls back to the persona's model when unset.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='nucleus.modelconfig'),
        ),
    ]
