# Generated by Django 5.2.17 on 2026-09-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleus', '0020_utility_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='acts_after_approval',
            field=models.BooleanField(default=False),
        ),
    ]
