# Generated by Django 5.2.17 on 2026-09-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleus', '0021_persona_acts_after_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='tool_levels',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
