# Generated by Django 5.2.17 on 2026-09-21 06:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleus', '0022_persona_tool_levels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='The /token: lowercase letters, digits and hyphens; unique per project.', max_length=40)),
                ('title', models.CharField(max_length=120)),
                ('purpose', models.CharField(blank=True, default='', max_length=200)),
                ('instructions', models.TextField(help_text='Markdown, at most 8,000 characters.')),
                ('allowed_capabilities', models.JSONField(blank=True, null=True)),
                ('is_builtin', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='nucleus.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_routines', to=settings.AUTH_USER_MODEL)),
                ('model_config', models.ForeignKey(blank=True, help_text="Overrides the persona's model for a reply run with this routine.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routines', to='nucleus.modelconfig')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='nucleus.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
