# Generated by Django 5.2.17 on 2026-09-21 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleus', '0023_routine'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaFallbackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fallback_links', to='nucleus.modelconfig')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fallback_links', to='nucleus.persona')),
            ],
            options={
                'db_table': 'intelligence_persona_fallback_model',
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='persona',
            name='fallback_models',
            field=models.ManyToManyField(blank=True, related_name='fallback_personas', through='nucleus.PersonaFallbackModel', to='nucleus.modelconfig'),
        ),
        migrations.AddConstraint(
            model_name='personafallbackmodel',
            constraint=models.UniqueConstraint(fields=('persona', 'model'), name='uniq_persona_fallback_model'),
        ),
        migrations.AddConstraint(
            model_name='personafallbackmodel',
            constraint=models.UniqueConstraint(fields=('persona', 'position'), name='uniq_persona_fallback_position'),
        ),
    ]
