# Generated by Django 5.2.17 on 2026-09-21 09:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleus', '0024_persona_fallback_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='recall_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='RecallEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('decision', 'Decision'), ('fact', 'Fact'), ('preference', 'Preference')], max_length=12)),
                ('text', models.CharField(max_length=500)),
                ('normalized', models.CharField(db_index=True, max_length=500)),
                ('author_persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recall_entries', to='nucleus.persona')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='nucleus.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recall_entries', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='nucleus.project')),
                ('source_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recall_entries', to='nucleus.chatmessage')),
                ('source_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recall_entries', to='nucleus.chattopic')),
            ],
            options={
                'db_table': 'intelligence_recall_entry',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'is_active'], name='intelligenc_project_0ac510_idx')],
            },
        ),
    ]
