# Generated by Django 5.2.17 on 2026-09-21 11:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleus', '0025_recall_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaschedule',
            name='persona',
            field=models.ForeignKey(blank=True, help_text='Existing persona to run the query against -- old or new, no restriction. Null when the schedule starts a runbook instead (W6).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='nucleus.persona'),
        ),
        migrations.CreateModel(
            name='Runbook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('steps', models.JSONField(default=list)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='nucleus.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_runbooks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='nucleus.project')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='personaschedule',
            name='runbook',
            field=models.ForeignKey(blank=True, help_text='The runbook this schedule starts each fire; the query_text is unused then.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='nucleus.runbook'),
        ),
        migrations.CreateModel(
            name='RunbookRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('stopped', 'Stopped')], db_index=True, default='queued', max_length=12)),
                ('current_step', models.IntegerField(default=-1)),
                ('step_results', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='nucleus.company')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='nucleus.project')),
                ('runbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='nucleus.runbook')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_runbook_runs', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runbook_runs', to='nucleus.chattopic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='runbook',
            index=models.Index(fields=['project', 'is_active'], name='nucleus_run_project_c6266a_idx'),
        ),
        migrations.AddIndex(
            model_name='runbookrun',
            index=models.Index(fields=['runbook', 'status'], name='nucleus_run_runbook_370e96_idx'),
        ),
        migrations.AddIndex(
            model_name='runbookrun',
            index=models.Index(fields=['topic', 'status'], name='nucleus_run_topic_i_fe0549_idx'),
        ),
    ]
