# Generated by Django 5.2.17 on 2026-09-21 12:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleus', '0026_runbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundHook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('label', models.CharField(blank=True, default='', help_text='What sends to this hook -- shown in the pane, never to the sender.', max_length=80)),
                ('token_hash', models.CharField(db_index=True, help_text='sha256 of the token. The token itself is shown once, at creation, and never stored.', max_length=64, unique=True)),
                ('token_hint', models.CharField(blank=True, default='', help_text="The token's last few characters, so two hooks can be told apart.", max_length=8)),
                ('is_paused', models.BooleanField(default=False)),
                ('last_fired_at', models.DateTimeField(blank=True, null=True)),
                ('fire_count', models.PositiveIntegerField(default=0)),
                ('last_status', models.CharField(choices=[('never_fired', 'Never fired'), ('success', 'Success'), ('failed', 'Failed')], default='never_fired', max_length=20)),
                ('last_error', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='nucleus.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hooks', to=settings.AUTH_USER_MODEL)),
                ('persona', models.ForeignKey(help_text='The persona a fire calls.', on_delete=django.db.models.deletion.CASCADE, related_name='inbound_hooks', to='nucleus.persona')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='nucleus.project')),
                ('topic', models.ForeignKey(help_text='The chat a fire posts into.', on_delete=django.db.models.deletion.CASCADE, related_name='inbound_hooks', to='nucleus.chattopic')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['topic', 'is_active'], name='nucleus_inb_topic_i_9946eb_idx')],
            },
        ),
    ]
