# Generated by Django 5.2.17 on 2026-09-21 13:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleus', '0027_inbound_hook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('html', 'Page'), ('chart', 'Chart'), ('table', 'Table'), ('form', 'Form'), ('text', 'Text')], default='text', max_length=12)),
                ('version', models.PositiveIntegerField(default=1)),
                ('content', models.TextField(help_text="Exactly what the reply carried -- the chart's JSON, the page's HTML.")),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='nucleus.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kept_deliverables', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='nucleus.project')),
                ('source_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliverables', to='nucleus.chatmessage')),
            ],
            options={
                'ordering': ['title', '-version'],
                'indexes': [models.Index(fields=['project', 'is_active'], name='nucleus_del_project_d0215e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('project', 'title', 'version'), name='one_version_per_title_per_project')],
            },
        ),
    ]
